#!/usr/bin/env bash
set -euo pipefail
# Download the repository
# Ensure that pixi is installed
# Move the desktop shortcut to the desktop

REPO_ZIP_URL="https://github.com/OrthoDriven/2d-point-annotator/archive/refs/heads/ajj/andrew-fixes.zip"
INSTALL_ROOT="$HOME/2d-point-annotator"
TMP_ZIP_FILE_PATH="$HOME/Downloads/2d-annotator.zip"

# Check to see if there is an existing installation to account for

if [ -d "$INSTALL_ROOT/app" ]; then
    rm -rf "$INSTALL_ROOT/app/"
fi

echo "Downloading application files..."

HTTP_CODE="$(curl -SL "$REPO_ZIP_URL" --output "$TMP_ZIP_FILE_PATH")" || CURL_ERR=$?

echo "Unzipping the files into $INSTALL_ROOT"

unzip -oq "$TMP_ZIP_FILE_PATH" -d "$INSTALL_ROOT"

TMP_PROJECT_DIR="$(find "$INSTALL_ROOT" -type f -name pixi.toml -not -path "$INSTALL_ROOT/old_app" -print0 -quit | xargs -0 dirname)"

PROJECT_DIR="$(dirname "$TMP_PROJECT_DIR")/app"

mv "$TMP_PROJECT_DIR" "$PROJECT_DIR"

if [ -d "$INSTALL_ROOT/old_app" ]; then
    rm -rf "$INSTALL_ROOT/old_app"
fi

# Check to see if pixi is installed onto the computer
if ! command -v pixi >/dev/null 2>&1; then
    echo "No pixi executable found, installing now!"
    curl -fsSL https://pixi.sh/install.sh | sh
else
    echo "Pixi executable found, skipping additional installation."
fi

ENV_FILE="$INSTALL_ROOT/app.env"
if ! [ -f "$ENV_FILE" ]; then
    mkdir -p "$(dirname "$ENV_FILE")"
    touch "$ENV_FILE"
fi

cat >"$ENV_FILE" <<EOF
# Auto-generated by installer on $(date)
USER_AGENT="2d-point-annotator-updater"
INSTALL_ROOT="$INSTALL_ROOT"
PROJECT_DIR="$PROJECT_DIR"
APP_DIR="$PROJECT_DIR"
REQUEST_TIMEOUT_SEC="15"
MIN_CHECK_INTERVAL_SECONDS="15"

# API that returns latest commit for a branch (example)
API_URL="https://api.github.com/repos/OrthoDriven/2d-point-annotator/commits/ajj/andrew-fixes"
REPO_ZIP_URL="$REPO_ZIP_URL"
EOF

if [ "$OSTYPE" == "darwin" ]; then
    echo "MacOS Detected!"
    ln -s "$PROJECT_DIR/install_scripts/UnixLauncher.sh" "$HOME/Desktop/Run_Annotator.command"
fi
